#!/usr/bin/env sh
# This script runs the pre-commit hook

# Run the pre-commit hook
echo "Running pre-commit hook"
npx lint-staged

# # Add the changes
echo "Adding changes to git"
git add .

if [ -z "$(git status --porcelain)" ]; then
  echo "No changes to commit"
  exit 0
fi

# Commit the changes with a message indicating that the pre-commit hook was run and skip the pre-commit hook
echo "Committing changes"
git commit -m "chore: pre-commit hook" --no-verify

# Push the changes
echo -e "\e[1;32mPushing changes\e[0m"
git push

# If the push failed, then exit with an error
if [ $? -ne 0 ]; then
  echo "Failed to push changes"
  exit 1
fi

# Exit successfully
echo "\e[1;32mSuccessfully pushed changes\e[0m"
exit 0

