#!/usr/bin/env sh
# This script runs the pre-commit hook

if [ -z "$(git status --porcelain)" ]; then
  echo "\n\e[1;31m----- No changes to commit -----\e[0m\n"
  exit 1
fi

# Run the pre-commit hook
echo "\n\e[1;32m***** START PRE-COMMIT HOOK *****\e[0m\n"

# Run lint-staged to check the files
echo "\n\e[1;32m***** Running lint-staged *****\e[0m\n"
npx lint-staged

# # Add the changes
echo "\n\e[1;32m***** Adding changes to git *****\e[0m\n"
git add .

# Commit the changes with a message indicating that the pre-commit hook was run and skip the pre-commit hook
echo "\n\e[1;32m***** Committing changes *****\e[0m\n"
git commit -m "chore: pre-commit hook" --no-verify

# Push the changes
echo "\n\e[1;32m***** Pushing changes *****\e[0m\n"
git push

# If the push failed, then exit with an error
if [ $? -ne 0 ]; then
echo "\n\e[1;31m----- Failed to push changes -----\e[0m\n"
  exit 1
fi

# Exit successfully
echo "\n\e[1;32m***** Successfully pushed changes *****\e[0m\n"

echo "\n\e[1;32m***** FINISHED PRE-COMMIT HOOK *****\e[0m\n"
exit 0

